### ISSUE TITLE
problem with quickrun-focus-p

### ISSUE THREAD

**Issue by sr105** [syohex/emacs-quickrun#67] opened 2015-11-22 21:27 UTC
When I run `M-x quickrun` repeatedly with the following setup, everything works. However, if I press Cmd-r repeatedly, the focus part only works the first time. On the second run, my cursor is placed in the quickrun buffer. Is there something else I need to do?

```
(require 'quickrun)
(global-set-key (kbd "s-r") 'quickrun)
(setq quickrun-focus-p nil)
```

**Comment by sr105** [comment] 2015-11-22 22:44
It only happens when the frame is split side-by-side via `C-x 3`, split-window-right.

**Comment by syohex** [comment] 2015-11-24 08:08
> However, if I press Cmd-s repeatedly,

What's Cmd-s ? Which command do you assign it ?

**Comment by sr105** [comment] 2015-11-24 13:33
> What's Cmd-s ? Which command do you assign it ?

    (global-set-key (kbd "s-r") 'quickrun)

It's right there. The Command key is the key used for "super" in Emacs on OSX (at least on my machine). Sorry, I thought that was obvious from my original code pasting.

**Comment by sr105** [comment] 2015-11-24 14:03
Here's a video of the bug. Running `M-x quickrun` works as expected, but running `quickrun` via the `s-r` shortcut works only on the first try. The problem only occurs for me when I'm in a side-by-side split and the quickrun output buffer is visible. If I switch to that window and replace it with another buffer, then after switching back to the window with the code, I can run quickrun via the shortcut and it works. But only once since the quickrun buffer is now visible.

![quickrun_bug](https://cloud.githubusercontent.com/assets/814760/11368811/beabafc4-9289-11e5-8e77-264746c7ca58.gif)

**Comment by sr105** [comment] 2015-11-24 16:36
I just re-read my initial post. I meant Cmd-r corresponding to `s-r`, sorry.

**Comment by krux02** [comment] 2017-01-13 21:53
I have the same problem problems. I hope there is still some activity here, because the last post is now more than one year ago.

**Comment by syohex** [comment] 2017-01-14 09:12
@sr105 @krux02 Sorry belated reply. I have fixed code at #85. Could you check latest version ?

**Comment by krux02** [comment] 2017-01-14 11:27
I just did the a quick run, several times, and it works. For me the issue is fixed.

**Closed** 2017-01-14 13:52 UTC

**Comment by syohex** [comment] 2017-01-14 13:57
Thanks for checking.
